name: Setup Environment
description: Checkout code, setup JDK and cache
runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-cache-${{ runner.os }}-
