package com.github.seepick.uscclient

import com.github.seepick.uscclient.model.City
import com.github.seepick.uscclient.model.Country
import org.jsoup.Jsoup

object CitiesGeneratorApp {
    @JvmStatic
    fun main(args: Array<String>) {
        val countries = parse()
        val result = buildString {
            appendLine("package com.github.seepick.uscclient.model")
            appendLine()
            appendLine("// generated by ${CitiesGeneratorApp::class.qualifiedName} in src/test/kotlin")
            appendLine("object CitiesCountries {")
            appendLine("    val allCountries = listOf(")
            countries.forEach { country ->
                appendLine("        Country(")
                appendLine("            label = \"${country.label}\",")
                appendLine("            cities = listOf(")
                country.cities.forEach { city ->
                    appendLine("                City(id = ${city.id}, label = \"${city.label}\"),")
                }
                appendLine("            ),")
                appendLine("        ),")
            }
            appendLine("    )")
            appendLine("}")

        }
        println()
        println(result)
        println()
    }

    private fun parse(): List<Country> {
        val html = Jsoup.parse(readFromClasspath("/cities.html"))
        return html.select("div.panel-default").map { countryHtml ->
            Country(
                label = countryHtml.select("span.usc-city-dropdown__country-name").text().trim(),
                cities =
                    countryHtml.select("a.usc-city-dropdown__city-link").map { cityHtml ->
                        City(
                            id = cityHtml.attr("data-id").toInt(),
                            label = cityHtml.select("span.usc-city-dropdown__city-name").text().trim(),
                        )
                    }
            )
        }
    }
}
